/** Clases de Niza (NCL) con descripción breve en español. */
export const NCL_CLASSES: Record<number, string> = {
  1: "Productos químicos",
  2: "Pinturas y barnices",
  3: "Cosméticos y limpieza",
  4: "Aceites y combustibles",
  5: "Productos farmacéuticos",
  6: "Metales comunes",
  7: "Máquinas y herramientas mecánicas",
  8: "Herramientas manuales",
  9: "Aparatos científicos y electrónicos",
  10: "Aparatos médicos",
  11: "Alumbrado y climatización",
  12: "Vehículos",
  13: "Armas de fuego",
  14: "Joyería y relojería",
  15: "Instrumentos musicales",
  16: "Papelería e imprenta",
  17: "Caucho y plásticos semielaborados",
  18: "Cuero y artículos de viaje",
  19: "Materiales de construcción no metálicos",
  20: "Muebles",
  21: "Utensilios domésticos",
  22: "Cuerdas y lonas",
  23: "Hilos textiles",
  24: "Tejidos y ropa de hogar",
  25: "Vestuario y calzado",
  26: "Encajes y adornos",
  27: "Alfombras y revestimientos",
  28: "Juegos y artículos deportivos",
  29: "Carne, pescado y lácteos",
  30: "Café, pan y pastelería",
  31: "Productos agrícolas y animales vivos",
  32: "Cervezas y bebidas sin alcohol",
  33: "Bebidas alcohólicas (excepto cervezas)",
  34: "Tabaco y artículos para fumadores",
  35: "Publicidad y gestión de negocios",
  36: "Servicios financieros y seguros",
  37: "Construcción y reparación",
  38: "Telecomunicaciones",
  39: "Transporte y almacenaje",
  40: "Tratamiento de materiales",
  41: "Educación y entretenimiento",
  42: "Servicios científicos y tecnológicos",
  43: "Restauración y hospedaje",
  44: "Servicios médicos y de belleza",
  45: "Servicios jurídicos y de seguridad",
};

export const NCL_CLASS_IDS = Object.keys(NCL_CLASSES).map(Number);
